### ISSUE TITLE
How to sign exe file with this plugin.

### ISSUE THREAD

**Issue by mubasherusman** [lukaszlenart/launch4j-maven-plugin#106]
Hi, 

I have successfully created the exe file with maven plugin but I am getting following warning. 
WARNING: Sign the executable to minimize antivirus false positives or use launching instead of wrapping.
So I tested this exe on a system where antivirus was installed and indeed antivirus treated the exe as virus.

So by searching on google I found there is sign4j included in laun4j desktop app. But I don't know how to use that or another way how to sign the exe file? 

Any help really appreciated.

Regards
~ Mubasher

**Comment by lukaszlenart** [comment]
Did you try to follow that https://sourceforge.net/p/launch4j/discussion/332684/thread/d4985f08/ ?

**Comment by sblantipodi** [comment]
@lukaszlenart is there a way to do it via maven?
thanks.

**Comment by lukaszlenart** [comment]
Looks like you can use this https://ebourg.github.io/jsign/
