### ISSUE TITLE
jni in path with lauch4j

### ISSUE THREAD

**Issue by rruffer** [lukaszlenart/launch4j-maven-plugin#109]
Hi,

Can you pass a -Djava.library.path to launch4j?

I start my application with a .bat by passing a -Djava.library.path. would you pass this information straight to the .exe created by lauch4j?

**Comment by lukaszlenart** [comment]
Not sure if I understand but you can use `<opts>` section to do so:

```
                <jre>
                  <minVersion>1.5.0</minVersion>
                  <opts>
                    <opt>-Djava.endorsed.dirs=./endorsed</opt>
                  </opts>
                </jre>
```

**Comment by lukaszlenart** [comment]
You can either hardcode such value with `<opts>` or define a [custom ini file](http://launch4j.sourceforge.net/docs.html#Additional_jvm_options)

**Comment by lukaszlenart** [comment]
This is rather a Launch4j problem itself, please search or ask question [here](https://sourceforge.net/p/launch4j/discussion/search/?q=taskbar+icon)
