### ISSUE TITLE
jar file too big - corrupted jar file

### ISSUE THREAD

**Issue by rladstaetter** [lukaszlenart/launch4j-maven-plugin#112]
i had a problem when packaging a jar file into an exe, which grew too big due to transitive dependencies. 

the jar file itself starts via 'java -jar xyz.jar' fine, but when i wrap it using this plugin i get an:

'Error: Invalid or corrupt jar file'

error message. Jar file size at about 113 MB, another version of this jar file with 112,9 MB works.

**Comment by lukaszlenart** [comment]
This plugin just wraps Launch4j and doesn't do any magic with jars, except that you can use Maven Assembly Plugin to create your own fat jar.

Did you try those:
https://stackoverflow.com/questions/41984193/launch4j-generated-exe-error-invalid-or-a-corrupt-jar-file
https://sourceforge.net/p/launch4j/bugs/169/
https://sourceforge.net/p/launch4j/discussion/332684/thread/888c30c1/

**Comment by rladstaetter** [comment]
thank you for your fast response.

in fact, if i circumvent wrapping the jar it runs perfectly fine. (using parameter 'dontWrapJar'). 

the bad thing about this is that then i have my exe AND my jar file. 

I'll close this issue, since I assume its more a problem of launch4j then.

**Comment by rladstaetter** [comment]
addendum: may well be i hit https://sourceforge.net/p/launch4j/bugs/169/ (>65k entries)
