### ISSUE TITLE
Exe not working when using 2 or more jre fallback paths

### ISSUE THREAD

**Issue by asiemsuk** [lukaszlenart/launch4j-maven-plugin#129]
From Launch4j 3.13, it added support to use JAVA_HOME and/or PATH environment variables to search for a runtime, if the registry keys is not found (See documentation at: http://launch4j.sourceforge.net/docs.html -> `<jre>` -> `<path>`).

I am using AdoptOpenJDK and it does not add the registry keys by default.

If I add `<path>%JAVA_HOME%;%PATH%</path>` (like the documentation example) to the `jre` configuration in the `pom.xml`, the generated exe will not work. But if I add only `<path>%JAVA_HOME%</path>` or `<path>%PATH%</path>`, the exe works fine.

**Comment by lukaszlenart** [comment]
Which version of the plugin did you use? Could you try to use 2.0.1?

**Comment by asiemsuk** [comment]
You are right !

I was using the plugin with no version specified. I thought it was using the latest version, but instead it was using 1.7.25.

Just updated to 2.0.1 and it works fine !!

Thanks
