### ISSUE TITLE
Suggestion: mkdirs in outfile path.

### ISSUE THREAD

**Issue by Tsyklop** [lukaszlenart/launch4j-maven-plugin#141]
I want to store all exe in `binary` folder in my maven project. But if I change path to:
```
${project.exe.folder.path}/binary/${application.name}-${application.version}.exe
```
And I got an error: `cannot open output file`.

Can you check folders, before start build exe file?

**Comment by lukaszlenart** [comment]
You mean that you have defined `outfile` to a folder that doesn't exist?

**Comment by Tsyklop** [comment]
@lukaszlenart yes.

**Comment by lukaszlenart** [comment]
Fixed and [released](https://github.com/lukaszlenart/launch4j-maven-plugin#version-notes-211---2021-05-04)!
