### ISSUE TITLE
Building Windows Executable on Yosemitee

### ISSUE THREAD

**Issue by fotisp** [lukaszlenart/launch4j-maven-plugin#16]
Hello All

I just added your plugin to see if I could create an executable binary, but I am getting the following error

```
net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: java.io.IOException: Cannot run program "/Users/fotis/.m2/repository/com/akathist/maven/plugins/launch4j/launch4j-maven-plugin/1.5.1/launch4j-maven-plugin-1.5.1-workdir-mac/bin/windres": error=86, Bad CPU type in executable
```

Throughout SO and Google it seems that Yosemite is the problem. 

Anyone here building on OSX and using this plugin?

Best,
Fotis

**Comment by lukaszlenart** [comment]
Can you try with newer version? 1.5.1 is a bit old ;-)

**Comment by fotisp** [comment]
Sorry for the spam, that one just went over my head!

Thank you!
