### ISSUE TITLE
Missing Java Runtime (OpenJDK)

### ISSUE THREAD

**Issue by M3ssman** [lukaszlenart/launch4j-maven-plugin#165]
# Description

Actual builds of a custom Maven-Desktop-Application with launch4J V2.1.1 seem to fail to locate a local, but non-bunled OpenJDK8 on Windows 11. 

(Earlier, the JRE used to be bundled in a Project-Subdir, which worked properly.)

Therefore it is not possible to use the created executable, but running the JAR say, with a *.bat file, works well.
According to this [documentation](http://launch4j.sourceforge.net/), only Oracle and IBM Java Version are respected - is that true?

**Comment by lukaszlenart** [comment]
I cannot answer your question as this project is a wrapper around Launch4j, please ask such questions on their [issue tracker](https://sourceforge.net/p/launch4j/bugs/).
And [this](https://sourceforge.net/p/launch4j/bugs/214/) looks like similar issue to yours.
