### ISSUE TITLE
Link src/main/resources/README from your README.md

### ISSUE THREAD

**Issue by virgo47** [lukaszlenart/launch4j-maven-plugin#18]
It contains important information but is difficult to find. :-) It helped us tremendously around classpath options. Please, link it or incorporate it into main README.MD directly as it helps big time.

If it's linked it would be great to transform it into MD format too. Talking about documentation, table mapping POM configuration options to original Launch4J options from http://launch4j.sourceforge.net/docs.html#Configuration_file would be also very helpful. Some are named a bit differently and one has to use examples or StackOverflow to get to desired result.

(Otherwise cool plugin, keep it up. :-))

**Comment by lukaszlenart** [comment]
Done, converted the README to AsciiDoc and linked to the main page
https://github.com/lukaszlenart/launch4j-maven-plugin#documentation
