### ISSUE TITLE
Using Launch4j  3.6

### ISSUE THREAD

**Issue by nroduit** [lukaszlenart/launch4j-maven-plugin#21]
Is it possible to update to the version 3.6? It seems that the plugin needs some modifications.

Because the following enhancements were eagerly awaited:
FR #86 The 32/64 bit search is fully configurable (64, 64/32, 32/64, 32) - added option 32/64.
FR #70 Java search sequence - bundled JRE can be used before or after the min/max version search

**Comment by lukaszlenart** [comment]
But such version isn't in Maven Central yet :(

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22net.sf.launch4j%22%20AND%20a%3A%22launch4j%22

**Comment by lukaszlenart** [comment]
3.8 was pushed to the Central
