### ISSUE TITLE
Cannot add dependency

### ISSUE THREAD

**Issue by Tutul-** [lukaszlenart/launch4j-maven-plugin#25]
First, thank for your plugin but I have a problem with it.
Actually, I use some library like apache-common but I cannot build (with assembly plugin) an exe with library in int :/
I try the addDependency param but didn't work (or I use it wrong ?). 
I try to build after the assembly plugin create the jar whit dependency but I didn't succeed :/
Can you tell me how to add these dependency in the exe ?
You can check the pom file there : https://github.com/Tutul-/NaheulCraft-Updater/blob/master/pom.xml

**Comment by lukaszlenart** [comment]
In configuration of assembly plugin you have `<finalName>${project.name}</finalName>` but in launch4j plugin you use `<jar>target/${project.artifactId}-${project.version}-${release.identifier}.jar</jar>`

What do you see in `target` folder after running `mvn assembly`?

**Comment by Tutul-** [comment]
The finalName must be remove but I see the ${project.artifactId}-${project.version}-${release.identifier}.jar and the version with dependency. And the exe without dependency (not working on Windows)

**Comment by lukaszlenart** [comment]
First of all: why do you need assembly-plugin? It isn't needed to run launch4j-plugin

**Comment by lukaszlenart** [comment]
Ok, I was able to find issue, but it's rather temporary fix and it would be better to clean up configuration.

Running `mvn assembly:single` will build `${project.name}-jar-with-dependencies.jar` in `target` so you must that jar in Launch4j's configuration

`<jar>target/${project.name}-jar-with-dependencies.jar</jar>`

**Comment by Tutul-** [comment]
ok I will do like that. But, I used assembly:assembly because before I used appbundle (for OSX but not used anymore actually). And appbundle pack the dependency within. but why launch4j does not?

**Comment by lukaszlenart** [comment]
Not sure why, by default `addDependency` flag is set to `true` so it should be there - will check some other options as well.

PS. `assembly:single` is the only valid option now, all others are deprecated - check page

**Comment by Tutul-** [comment]
you can check the new version of the pom file. But launch4j not working anymore without assembly:assembly. The mvn command is "launch4j:launch4j" no ? He tell me headerType and jre are not good. I try with assembly:assembly and all work

**Comment by Tutul-** [comment]
ok I use shade now and I must specified the shaded jar (so launch4j didn't include dependency). But I must use the <id>default-cli</id> with <headerType>gui</headerType> (because maven only execut default-cli, jow can I specify the l4j-gui id for maven to execut it ?)

**Comment by lukaszlenart** [comment]
Can you try with the latest plugin version? I have tested your project locally and it supposed to works.

**Comment by Tutul-** [comment]
I'll try that these week-end :)

**Comment by Tutul-** [comment]
Seems to be ok :) thanks ^^
