### ISSUE TITLE
<opt> under <jre> does not seem to be supported

### ISSUE THREAD

**Issue by yairoren** [lukaszlenart/launch4j-maven-plugin#26]
<opt> under <jre> allows specification of JVM options and apparently is not supported by this plugin. Is there another way to achieve this?

**Comment by yairoren** [comment]
Never mind... looked at the code and realized I can use an .l4j.ini file

**Comment by flashpixx** [comment]
I need to use the <opt> flag of launch4j, because I need to setup the -Xmx flags. How can I do this with the plugin?

**Comment by lukaszlenart** [comment]
Have you tried to use:
```xml
<jre>
  <opts>
   <opt>-Xmx1024</opt>
  </opts>
</jre>
```
?
