### ISSUE TITLE
Locale settings ignored

### ISSUE THREAD

**Issue by jesperlehtinen** [lukaszlenart/launch4j-maven-plugin#33]
Not sure if this is a problem with the maven plugin or the actual source. I'll post here anyway.

I wrap a Java Swing client with the Launch4j maven plugin (version 1.7.8), and I'm trying to get text fields to use Swedish locale (number formatting, currency). I've noticed that the locale settings seems to be forced to en-US when we use Launch4j. I've confirmed this by running the original .jar with cmd, and a text field displays the number 12345 as "12 345" (Swedish locale). When I run the executable generated by Launch4j, the text field displays "12,345" (English locale).

I've tried setting <opt>-Duser.language=sv</opt> and <opt>-Duser.country=SE</opt> in <jre> opts, and also specifying locale programatically in a static context in Java.

**Comment by lukaszlenart** [comment]
Could you share you pom.xml?

**Comment by jesperlehtinen** [comment]
relevant part of pom.xml: http://pastebin.com/LeBr1mPh

**Comment by jesperlehtinen** [comment]
Nevermind -- turns out this was related to the JRE we bundle with our app, and not related to the executable itself.
