### ISSUE TITLE
Error building on Mac

### ISSUE THREAD

**Issue by zachm93** [lukaszlenart/launch4j-maven-plugin#34]
Caused by: org.apache.maven.plugin.MojoExecutionException: Launch4j native configuration file [/path/to/tool/src/main/resources/toolname-launch4j.xml] does not exist!

**Comment by lukaszlenart** [comment]
Is it related to the latest 1.7.9 version? Could you share your pom.xml?

**Comment by zachm93** [comment]
Yes, it only happens in the latest version.

<plugin>
                <groupId>com.akathist.maven.plugins.launch4j</groupId>
                <artifactId>launch4j-maven-plugin</artifactId>
                <version>1.7.8</version>
                <executions>
                    <execution>
                        <id>l4j-gui</id>
                        <phase>package</phase>
                        <goals>
                            <goal>launch4j</goal>
                        </goals>
                        <configuration>
                            <headerType>gui</headerType>
                            <dontWrapJar>false</dontWrapJar>
                            <outfile>${project.build.directory}/Executables/${project.name}.exe</outfile>
                            <jar>${project.build.directory}/Executables/${project.name}.jar</jar>
                            <errTitle>${project.name}</errTitle>
                            <priority>normal</priority>
                            <stayAlive>false</stayAlive>
                            <jre>
                                <minVersion>${compiler.version}.0</minVersion>
                            </jre>
                            <classPath>
                                <addDependencies>true</addDependencies>
                                <mainClass>${project.mainClass}</mainClass>
                            </classPath>
                            <icon>${basedir}/build-resources/favicon.ico</icon>
                            <versionInfo>
                                <fileVersion>0.${app.version}</fileVersion>
                                <txtFileVersion>0.${app.version}</txtFileVersion>
                                <productVersion>0.${app.version}</productVersion>
                                <txtProductVersion>0.${app.version}</txtProductVersion>
                                <fileDescription>${project.name}</fileDescription>
                                <internalName>${project.name}</internalName>
                                <copyright>Copyright (C) 2013-2016 Company</copyright>
                                <productName>${project.name}</productName>
                                <companyName>Company</companyName>
                                <originalFilename>${project.name}.exe</originalFilename>
                            </versionInfo>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by lukaszlenart** [comment]
but you are using `1.7.8`, right?

**Comment by lukaszlenart** [comment]
and your example pom is missing `<infile>`

**Comment by zachm93** [comment]
Ah, I didn't read the update instructions. I reverted to 1.7.8, yes.

Does 1.7.8 generate a temporary xml infile somewhere? I wont update if the new version requires me to create it, the plugin has been working fine without one.

**Comment by lukaszlenart** [comment]
With new version you can either use your existing configuration (as above) or you can use external file via `<infile>` (which is native Launch4j config http://launch4j.sourceforge.net/docs.html#Configuration_file)

**Comment by lukaszlenart** [comment]
I have extended [README](https://github.com/lukaszlenart/launch4j-maven-plugin/blob/master/README.md#version-notes-179) about that info

**Comment by zachm93** [comment]
Okay, thanks for the info!
