### ISSUE TITLE
New <infile> makes older configuration no longer possible

### ISSUE THREAD

**Issue by mihaitudor** [lukaszlenart/launch4j-maven-plugin#35]
After updating to the latest version I was no longer able to use the previous configuration which had no <infile> element.  I get an exception saying that the **Launch4j native configuration file does not exist**.  I  looked at the source code, and I believe the problem is that the infile field's default value is set through the @Property annotation which makes the inexistence of the <infile> element invisible to the plugin.

**Comment by lukaszlenart** [comment]
Can you share your pom.xml?

**Comment by TiBeN** [comment]
Same here

**Comment by mihaitudor** [comment]
Sorry, I was away for a while. My pom is pretty big and it depends on other big poms, I'll try to extract the relevant part and make a small example project.

**Comment by TiBeN** [comment]
Mine on my project can be viewed publicly : <https://github.com/TiBeN/ia-mame/blob/master/pom.xml>

Simply remove the plugin version tags:
```
<version>1.7.8</version> 
```

**Comment by lukaszlenart** [comment]
Just pushed a new version to Central
