### ISSUE TITLE
NullPointerException, missing headerType... Except it's there.

### ISSUE THREAD

**Issue by BugFactory323** [lukaszlenart/launch4j-maven-plugin#36]
Hello. I just tried using launch4j-maven-plugin but I can't make it work. I get the following error ;
```
[ERROR] Failed to execute goal com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.7.10:launch4j (default-cli) on project gaiaTerminal: Execution default-cli of goal com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.7.10:launch4j failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.7.10:launch4j (default-cli) on project gaiaTerminal: Execution default-cli of goal com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.7.10:launch4j failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.7.10:launch4j failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.NullPointerException
	at net.sf.launch4j.config.Config.getHeaderType(Config.java:195)
	at net.sf.launch4j.config.Config.checkInvariants(Config.java:136)
	at net.sf.launch4j.config.Config.validate(Config.java:154)
	at net.sf.launch4j.Builder.build(Builder.java:74)
	at com.akathist.maven.plugins.launch4j.Launch4jMojo.execute(Launch4jMojo.java:358)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
```

I checked my pom file but headerType was there. I tried replacing my configuration with the one straight from the documentation, changing only the main class, but I got the same error. Here is the relevant part of the pom file :
```<plugin>
	<groupId>com.akathist.maven.plugins.launch4j</groupId>
	<artifactId>launch4j-maven-plugin</artifactId>
	<executions>
		<execution>
			<id>l4j-clui</id>
			<phase>package</phase>
			<goals>
				<goal>launch4j</goal>
			</goals>
			<configuration>
				<headerType>console</headerType>
				<outfile>target/encc.exe</outfile>
				<jar>target/encc-1.0.jar</jar>
				<errTitle>encc</errTitle>
				<classPath>
					<mainClass>com.bonduelle.gaia.GaiaTerminal</mainClass>
					<addDependencies>false</addDependencies>
					<preCp>anything</preCp>
				</classPath>
				<jre>
					<minVersion>1.5.0</minVersion>
					<opts>
						<opt>-Djava.endorsed.dirs=./endorsed</opt>
					</opts>
				</jre>
				<versionInfo>
					<fileVersion>1.2.3.4</fileVersion>
					<txtFileVersion>txt file version?</txtFileVersion>
					<fileDescription>a description</fileDescription>
					<copyright>my copyright</copyright>
					<productVersion>4.3.2.1</productVersion>
					<txtProductVersion>txt product version</txtProductVersion>
					<productName>E-N-C-C</productName>
					<internalName>ccne</internalName>
					<originalFilename>original.exe</originalFilename>
				</versionInfo>
			</configuration>
		</execution>
	</executions>
</plugin>
```

Any idea what is wrong? Thanks in advance.

**Comment by lukaszlenart** [comment]
What version of `launch4j-maven-plugin` do you use?

**Comment by BugFactory323** [comment]
Thanks for answering.

I added <version>1.7.10</version> to the pom to make sure it's the latest version. Nothing changed. I tried 1.7.9 and the error became org.apache.maven.plugin.MojoExecutionException: Launch4j native configuration file [D:\JavaFx\workspace\gaiaTerminal\src\main\resources\gaiaTerminal-launch4j.xml] does not exist!

Also, I'm running Maven 3.3.3.

**Comment by BugFactory323** [comment]
I tried putting a breakpoint in com.akathist.maven.plugins.launch4j.Launch4jMojo at line 358 (builder.build();) and this.headerType is indeed null, as are chdir, classpath, etc. It seems the configuration is not read.

**Comment by lukaszlenart** [comment]
Could you share the whole pom.xml?

**Comment by lukaszlenart** [comment]
I want to be sure you are using the plugin as [here](https://github.com/lukaszlenart/launch4j-maven-plugin/blob/master/src/main/resources/README.adoc#single-module-project)

**Comment by BugFactory323** [comment]
I think I found the issue. I was trying to launch the build using the launch4j goal. The plugin works if I use the install goal. Is this the intended behavior?

Anyway, here is the pom file.
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.bonduelle.gaia</groupId>
	<artifactId>gaiaTerminal</artifactId>
	<version>1.0.0</version>
	<name>Gaïa Terminal</name>
	<description>Logiciel de contrôle des bornes Gaïa</description>
	<organization>
		<name>Bonduelle</name>
	</organization>

	<properties>
		<spring.version>4.0.5.RELEASE</spring.version>
		<jackson.version>2.7.2</jackson.version>
		<slf4j.version>1.7.19</slf4j.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		
		<appName>Terminal Gaia</appName>
		
		<fileName>GaiaTerminal</fileName>
		
		<mainClass>com.bonduelle.gaia.GaiaTerminal</mainClass>
	</properties>

	<dependencies>
		
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
			<version>${spring.version}</version>
			<exclusions>
				
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
			<version>${spring.version}</version>
		</dependency>

		
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.4</version>
		</dependency>

		
		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
			<version>1.10</version>
		</dependency>

		
		<dependency>
			<groupId>com.bonduelle.nfc</groupId>
			<artifactId>nfc</artifactId>
			<version>1.0.0</version>
		</dependency>

		
		
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>${jackson.version}</version>
		</dependency>
		
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<version>${jackson.version}</version>
		</dependency>
		
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>${jackson.version}</version>
		</dependency>
		
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-jsr310</artifactId>
			<version>2.6.1</version>
		</dependency>

		
		<dependency>
			<groupId>com.bonduelle.pontBascule</groupId>
			<artifactId>pontBascule</artifactId>
			<version>1.0.0</version>
		</dependency>

		
		
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>${slf4j.version}</version>
		</dependency>
		
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.1.6</version>
		</dependency>
		
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>jcl-over-slf4j</artifactId>
			<version>${slf4j.version}</version>
		</dependency>

		
		<dependency>
			<groupId>com.bonduelle.gaia</groupId>
			<artifactId>smartCardsWin32Utilities</artifactId>
			<version>1.0.0</version>
		</dependency>
	</dependencies>

	<build>
		<finalName>${fileName}</finalName>

		
		<resources>
			<resource>
				<directory>src/main/java</directory>
				<excludes>
					<exclude>**/*.java</exclude>
				</excludes>
			</resource>
		</resources>

		<plugins>
			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.5.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>2.6</version>
				<configuration>
					<archive>
						<manifest>
							<addClasspath>true</addClasspath>
							<mainClass>${mainClass}</mainClass>
						</manifest>
					</archive>
				</configuration>
			</plugin>
			
			<plugin>
				<groupId>com.zenjava</groupId>
				<artifactId>javafx-maven-plugin</artifactId>
				<version>8.2.0</version>
				<configuration>
					<mainClass>${mainClass}</mainClass>
				</configuration>
			</plugin>
			
			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<archive>
						<manifest>
							<mainClass>${mainClass}</mainClass>
						</manifest>
					</archive>
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
				</configuration>
				<executions>
					<execution>
						<id>make-assembly</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			
			<plugin>
				<groupId>com.akathist.maven.plugins.launch4j</groupId>
				<artifactId>launch4j-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>l4j-clui</id>
						<phase>package</phase>
						<goals>
							<goal>launch4j</goal>
						</goals>
						<configuration>
							<headerType>console</headerType>
							<outfile>target/encc.exe</outfile>
							<jar>target/GaiaTerminal-jar-with-dependencies.jar</jar>
							<errTitle>encc</errTitle>
							<classPath>
								<mainClass>com.bonduelle.gaia.GaiaTerminal</mainClass>
								<addDependencies>false</addDependencies>
								<preCp>anything</preCp>
							</classPath>
							<jre>
								<minVersion>1.5.0</minVersion>
								<opts>
									<opt>-Djava.endorsed.dirs=./endorsed</opt>
								</opts>
							</jre>
							<versionInfo>
								<fileVersion>1.2.3.4</fileVersion>
								<txtFileVersion>txt file version?</txtFileVersion>
								<fileDescription>a description</fileDescription>
								<copyright>my copyright</copyright>
								<productVersion>4.3.2.1</productVersion>
								<txtProductVersion>txt product version</txtProductVersion>
								<productName>E-N-C-C</productName>
								<internalName>ccne</internalName>
								<originalFilename>original.exe</originalFilename>
							</versionInfo>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
`

The launch4j configuration is at the end.

**Comment by lukaszlenart** [comment]
It's up to you, you defined `<phase>package</phase>` which is one phases in `install` phase, that's how it works. There is no configuration for `<goal>launch4j</goal>`, you can have few different configurations depending on phases, that's how Maven plugins work. Take a look on this [guide](https://maven.apache.org/guides/mini/guide-configuring-plugins.html) there are two examples where configuration is defined per plugin and per execution. Compare the above:

```
<plugin>
    <groupId>com.akathist.maven.plugins.launch4j</groupId>
    <artifactId>launch4j-maven-plugin</artifactId>
    <configuration>
      ...
```

```
<plugin>
    <groupId>com.akathist.maven.plugins.launch4j</groupId>
    <artifactId>launch4j-maven-plugin</artifactId>
    <executions>
      <execution>
        ...
      <configuration>
         ...
```

**Comment by BugFactory323** [comment]
Thanks for your help.
