### ISSUE TITLE
New release with Launch4J 3.9

### ISSUE THREAD

**Issue by sarumont** [lukaszlenart/launch4j-maven-plugin#43]
Please build a new release packaging [Launch4J 3.9](http://launch4j.sourceforge.net/changelog.html). The big bugfix is: 

 > Ticket #146 Fixed java version check where the update number was greater than 99 (e.g. 1.8.0_101).

Thanks!

**Comment by lukaszlenart** [comment]
Also `<headerType>gui|console|jniGui32|jniConsole32</headerType>` :) I will do it next week probably

**Comment by lukaszlenart** [comment]
Fixed with de5f7edac4fda1317642e48a30f399ca0a668ed5
