### ISSUE TITLE
Cannot find 'language' in class com.akathist.maven.plugins.launch4j.VersionInfo

### ISSUE THREAD

**Issue by dyorgio** [lukaszlenart/launch4j-maven-plugin#45]
Plugin is not supporting versioninfo inner \<language\> tag:

Unable to parse configuration of mojo com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.7.11:launch4j for parameter language: Cannot find 'language' in class com.akathist.maven.plugins.launch4j.VersionInfo.

**Comment by lukaszlenart** [comment]
Done, added missing options with 181a009cfcffdb1bdee867fb55d02b1c27ff7e13

**Comment by lukaszlenart** [comment]
1.7.12 is under way to the Maven Central, please test and report back

**Comment by lukaszlenart** [comment]
Be sure that there is no non-printable character or something in `<language>ENGLISH_US</language>` - if problem persists please report issue directly to [Launch4j](https://sourceforge.net/p/launch4j/bugs/)
