### ISSUE TITLE
How would I confiure this to package an exe with some excluded jars?

### ISSUE THREAD

**Issue by MiroslavMarecek** [lukaszlenart/launch4j-maven-plugin#46]
Hi, I'm having some trouble getting this to work. I already posted a question on SO, but to no avail. Here goes the description:

I'm developing an app that takes some arguments, sends some data to a server, and receives a response. It will only be called by another app and only uses CLI interface. Its dependencies are resolved by Maven. I need to package it into an .exe(legacy reasons). Also, one of the dependencies of my app uses some Bouncy Castle jars, which cannot be packaged normally with Maven assembly plugin because they lose their signatures.

As a solution, it has been suggested to me in another question that I use Launch4j plugin to both exclude the BC jars and build the exe. However, I can't for the life of me figure out how to configure it correctly. I did wiggle around a bit and changed some stuff, but there's just too much knowledge that I'm lacking and too much crapslinging to lead to a solution. Your example POM only shows(so far as I understand with my limited grasp on Maven) how to make an .exe and then package _that_ into a jar, the exact opposite of what I need.

Could you then please have a look at [this question](http://stackoverflow.com/questions/39997888/maven-launch4j-plugin-how-to-configure-to-exclude-jars-used-by-the-exe) and tell me what POM exacly would I need to achieve this result, or if the advice to use Launch4j instead of shade for my purpose is even viable? I'm quite lost on the issue, and I would be extremely grateful for any help.

Current POM:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <packaging>jar</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>com.akathist.maven.plugins.launch4j</groupId>
                <artifactId>launch4j-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>l4j-clui</id>
                        <phase>package</phase>
                        <goals>
                            <goal>launch4j</goal>
                        </goals>
                        <configuration>
                            <dontWrapJar>false</dontWrapJar>
                            <headerType>console</headerType>
                            <jar>target\eet-demo-maven-1.0-SNAPSHOT.jar</jar>
                            <outfile>target\EETSender.exe</outfile>
                            <errTitle></errTitle>
                            <cmdLine></cmdLine>
                            <chdir>.</chdir>
                            <priority>normal</priority>
                            <downloadUrl>http://java.com/download</downloadUrl>
                            <supportUrl></supportUrl>
                            <stayAlive>true</stayAlive>
                            <restartOnCrash>true</restartOnCrash>
                            <manifest></manifest>
                            <icon></icon>
                            <singleInstance>
                                <mutexName>EETMutex</mutexName>
                                <windowTitle></windowTitle>
                            </singleInstance>
                            <classPath>
                                <mainClass>cz.tomasdvorak.eetdemo.Main</mainClass>
                                <addDependencies>true</addDependencies>
                            </classPath>
                            <jre>
                                <path></path>
                                <bundledJre64Bit>false</bundledJre64Bit>
                                <bundledJreAsFallback>false</bundledJreAsFallback>
                                <minVersion>1.6.0_1</minVersion>
                                <maxVersion></maxVersion>
                                <jdkPreference>preferJre</jdkPreference>
                                <runtimeBits>64/32</runtimeBits>
                            </jre>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <id>assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <archive>
                                <manifest>
                                    <addClasspath>true</addClasspath>
                                    <mainClass>cz.tomasdvorak.eetdemo.Main</mainClass>
                                </manifest>
                            </archive>
                            <descriptors>
                                <descriptor>assembly.xml</descriptor>
                            </descriptors>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

    <groupId>cz.tomasdvorak</groupId>
    <artifactId>eet-demo-maven</artifactId>
    <version>1.0-SNAPSHOT</version>

    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.github.todvora</groupId>
            <artifactId>eet-client</artifactId>
            <version>1.2</version>
        </dependency>
    </dependencies>

</project>
```

**Comment by lukaszlenart** [comment]
It would be better if you could setup a small demo app on GitHub - then I can use it and test.

**Comment by Sargon1** [comment]
Hi,

thanks for replying. I can't seem to be able to upload the files right now,
but I'll do it as soon as I get to some normal internet connection.

2016-10-12 16:10 GMT+02:00 Lukasz Lenart <notifications@github.com>:

**Comment by Sargon1** [comment]
Hi again, I can't get github to work and I'm a bit pressed for time these
days. I know it's not as convenient, but could you make do with a .zip file
instead? I hope I packaged it properly, Eclipse broke as well and I'm too
busy to try to hunt down the error right now. Also, here are some of my
previous question on SO related to the problem:

Pretty much the problem I described on GitHub:
http://stackoverflow.com/questions/39997888/maven-launch4j-plugin-how-to-configure-to-exclude-jars-used-by-the-exe

A previous question a further down this particular line of bugs:
http://stackoverflow.com/questions/39993855/maven-assembly-jar-jce-cannot-authenticate-the-provider-bc

I'll try to check mail more often to be more responsive.

2016-10-13 14:12 GMT+02:00 Miroslav Mareček <miroslavmarecek@gmail.com>:

**Comment by lukaszlenart** [comment]
Just create a repo on GitHub and push your files

**Comment by Sargon1** [comment]
Took some convincing, but I finlly got the files there:
https://github.com/Sargon1/eet-demo-maven

2016-10-13 20:17 GMT+02:00 Lukasz Lenart <notifications@github.com>:

**Comment by akuhtz** [comment]
Hi Miroslav,

Have you ever tried if `<dontWrapJar>true</dontWrapJar>` solves your problem?
This should not touch the bouncycast or any other dependency, because the exe no longer contains the classes from the dependencies.
