### ISSUE TITLE
Access to change tmp directory in plugin configuration

### ISSUE THREAD

**Issue by heathjmorgange** [lukaszlenart/launch4j-maven-plugin#52]
I am encountering a problem where on parallel builds, it appears that I have on at least one occasion gotten the result where one application built by launch4j had the icon from another application being built by launch4j at the same time.

It looks like there is an option in launch4j to change the tmp or working directory (`launch4j.tmpdir` or `tmpdir`, I'm not quite sure how to read their documentation for thisin launch4j itself), but this `launch4j-maven-plugin` does not seem to provide access to it.  Am I missing something?

**Comment by lukaszlenart** [comment]
`launch4j.tmpdir` isn't exposed to be changeable programmatically but it looks like you can define it as `-Dlaunch4j.tmpdir=/path/to/tmp` when starting Maven or inside a `pom.xml`

```xml
    <build>
      <plugins>
        <plugin>
          <groupId>com.akathist.maven.plugins.launch4j</groupId>
          <artifactId>launch4j-maven-plugin</artifactId>
          <configuration>
            <systemPropertyVariables>
              <launch4j.tmpdir>/path/to/tmp</launch4j.tmpdir>
            </systemPropertyVariables>
          </configuration>
     ...
```

**Comment by lukaszlenart** [comment]
http://maven.apache.org/surefire/maven-surefire-plugin/examples/system-properties.html

**Comment by heathjmorgange** [comment]
Thanks!  This will work for me...
