### ISSUE TITLE
Workdir issues

### ISSUE THREAD

**Issue by Tillerino** [lukaszlenart/launch4j-maven-plugin#53]
I am running the launch4j maven plugin in an automated build through gitlab runner on a windows server and it is using the system profile. The command

```
C:\Windows\system32\config\systemprofile\.m2\repository\net\sf\launch4j\launch4j\3.9\launch4j-3.9-workdir-win32\bin\ld.exe
-mi386pe --oformat pei-i386 --dynamicbase --nxcompat --no-seh --subsystem windows -s
C:\Windows\system32\config\systemprofile\.m2\repository\net\sf\launch4j\launch4j\3.9\launch4j-3.9-workdir-win32\w32api\crt2.o
C:\Windows\system32\config\systemprofile\.m2\repository\net\sf\launch4j\launch4j\3.9\launch4j-3.9-workdir-win32\head\guihead.o
C:\Windows\system32\config\systemprofile\.m2\repository\net\sf\launch4j\launch4j\3.9\launch4j-3.9-workdir-win32\head\head.o
C:\Windows\TEMP\launch4j4260037253500529036o
C:\Windows\system32\config\systemprofile\.m2\repository\net\sf\launch4j\launch4j\3.9\launch4j-3.9-workdir-win32\w32api\libmingw32.a
...
```
(line breaks for readability) fails with serveral messages:

```
[INFO] --- launch4j-maven-plugin:1.7.15:launch4j (default) @ danae ---
[INFO] launch4j: Compiling resources
[INFO] launch4j: Linking
[INFO] launch4j: C:\Windows\system32\config\systemprofile\.m2\repository\net\sf\launch4j\launch4j\
3.9\launch4j-3.9-workdir-win32\bin\ld.exe: cannot find C:\Windows\system32\config\systemprofile\
.m2\repository\net\sf\launch4j\launch4j\3.9\launch4j-3.9-workdir-win32\w32api\crt2.o: No such file or directory
[INFO] launch4j: C:\Windows\system32\config\systemprofile\.m2\repository\net\sf\launch4j\launch4j\
3.9\launch4j-3.9-workdir-win32\bin\ld.exe: cannot find C:\Windows\system32\config\systemprofile
\.m2\repository\net\sf\launch4j\launch4j\3.9\launch4j-3.9-workdir-win32\head\guihead.o: No such file or directory
...
```
(again line breaks for readability)
I can't figure out why this fails. The files do exist. When I call the command manually from the command line with my regular windows user, it fails as well. If I move the w32api folder to a different location, say `C:\win32api`, and modify the command accordingly, `ld.exe` can suddenly find the files.

I suspect that this is somehow an issue with the system profile / SYSTEM user. I saw in the code that there is this whole rationale behind extracting the workdir into the maven repository. Is it at all feasible to use a temp folder instead?

**Comment by lukaszlenart** [comment]
Do you get any exception? Or can you start Maven in debug mode?

**Comment by Tillerino** [comment]
The error message from the maven plugin is simply

```
Failed to execute goal com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.7.15:launch4j
(default) on project danae: Failed to build the executable; please verify your configuration.
net.sf.launch4j.ExecException: Exec failed (1):
C:\Windows\system32\config\systemprofile\.m2\repository\net\sf\launch4j\launch4j\3.9\launch4j-3.9-workdir-win32\bin\ld.exe
-mi386pe --oformat pei-i386 --dynamicbase --nxcompat --no-seh --subsystem windows -s
C:\Windows\system32\config\systemprofile\.m2\repository\net\sf\launch4j\launch4j\3.9\launch4j-3.9-workdir-win32\w32api\crt2.o
...
```
(and then the entire command)

This accurate. When I call that command by hand, it does fail, saying that it is missing all the files listed above. Somehow `ld.exe` has a problem with that particular workdir.

**Comment by lukaszlenart** [comment]
I know that but I wonder if it's a problem with extracting files (and that's why I haved asked about the exception) or maybe a path is too long

**Comment by Tillerino** [comment]
The files are all there.

**Comment by Tillerino** [comment]
I suspected the length of the path as well and moved the files to a location with a longer path name. The length of the path didn't seem to cause the issue.

**Comment by lukaszlenart** [comment]
I'm not sure if moving files to different location do any difference, looks like issue with privileges. I assume you cannot run this job as a normal user?

**Comment by Tillerino** [comment]
Not sure if it's privileges or the location. I'll try running the service with a non-system user.

**Comment by Tillerino** [comment]
That works just fine.

**Comment by lukaszlenart** [comment]
?

**Comment by Tillerino** [comment]
I am using a regular windows user (not SYSTEM) to run the gitlab runner service now. The maven plugin works fine like that.

Thing is that _both_ properties in question changed. The location and the user. So this didn't help in figuring out if it is the _path_ that is causing the problems or the _access rights_. Both look normal to me tbh.

**Comment by lukaszlenart** [comment]
Please re-open if something new will happen

**Comment by kigero** [comment]
I had this problem as well; in my case it wasn't permissions related, it was strictly the length of the path.  I moved my repository location out of the home directory and into the root directory and the plugin worked as expected.
