### ISSUE TITLE
workdir-osx:3.11 missing

### ISSUE THREAD

**Issue by marco-brandizi** [lukaszlenart/launch4j-maven-plugin#58]
Trying to build with 1.7.19 on macOS 10.12.6 (pom [here](https://github.com/Rothamsted/ondex-desktop/blob/master/ovtk2/pom.xml)) and it fails with this message:

`[ERROR] Failed to execute goal com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.7.19:launch4j (l4j-gui) on project ovtk2: Can't find platform-specific components: Could not find artifact net.sf.launch4j:launch4j:jar:workdir-osx:3.11`

Going back to 1.7.16 and it seems to work. Maybe it's related to #54

**Comment by lukaszlenart** [comment]
Looks like this is related to this change - right now there is only one package for OSX
https://sourceforge.net/p/launch4j/bugs/160/#59fc

**Comment by lukaszlenart** [comment]
Exactly, right now there is just one package for OSX called `mac`
http://uk.maven.org/maven2/net/sf/launch4j/launch4j/3.11/

**Comment by marco-brandizi** [comment]
Hi @lukaszlenart, thank you for having reviewed this. So, is the issue fixed? Will the next version of launch-4j work on my Mac? Or should I do some more config?

**Comment by lukaszlenart** [comment]
Please check 1.7.21, it should work without any change in your config.

**Comment by marco-brandizi** [comment]
Cool! It works now! Thanks again.
