### ISSUE TITLE
Question about head subproject licensing ?

### ISSUE THREAD

**Issue by ihbar** [lukaszlenart/launch4j-maven-plugin#60]
Hello

In the file "License", there is the mention "The Head subproject (the code which is attached to the wrapped jars) is licensed under the GNU Lesser General Public License."

In Launch4J, since version 3, it is now MIT license, and the headers of the "head" source code in the launch4j-maven-plugin project seems to be also MIT compliant. (not LGPL).  
So I think there is no more LGPL in Launch4J part.
Can you confirm and update the license information ?  

Thank you

Stephane

**Comment by lukaszlenart** [comment]
I think this can throw away, the plugin doesn't wrap Launch4j jars anymore, it uses direct dependencies from Maven repository.

**Comment by lukaszlenart** [comment]
I have removed the proprietary code from the plugin source and removed the sentence related to Launch4j itself.

**Comment by ihbar** [comment]
Hello Lukasz.

Thanks a lot for the answer and the rework you have done.  I did no expect that my question would generate so much work. 
This is solving the dependency with Launch4j licensing.

And thanks a lot for the plugin, it is very usefull for me. 

Stephane
