### ISSUE TITLE
building product.exe and final assembly  layout

### ISSUE THREAD

**Issue by bamcgill** [lukaszlenart/launch4j-maven-plugin#66]
Hi Lukasz,

I'm building an exe in target/product.exe from a jar abc-snapshot.jar.
In my assembly, I am putting together the layout for the product with a bin directory and a lib directory.
My bin directory contains my product.exe and my product.sh and my lib dir contains my dependency libraries. and my abc-snapshot gets renamed to abc.jar

Before creation of the product.exe my layout doesnt exist. so when I build it and lay it in, the main class is not found as my jar name changes.

Is there any 'easy' way to set this up with out creating the assembly, unzipping it, creating the product.exe again and dropping it in?

Thanks
Barry

**Comment by lukaszlenart** [comment]
I think you can use `dontWrap` option and to put you renamed jar next to the exe

https://stackoverflow.com/questions/9281081/using-launch4j-when-should-i-wrap-the-jar
