### ISSUE TITLE
Splash screen is not shown when created with the Maven plug-in

### ISSUE THREAD

**Issue by Forgev41** [lukaszlenart/launch4j-maven-plugin#69]
The issue is that the Splash screen is not shown at the start of the Windows executable when build with the plugin.
HOWEVER it does show when run with Java -JAR and also when the EXE is created with the Launch4J GUI program.
To reproduce this issue I created a very simple Java Swing application which says Hello World
[Github](https://github.com/Forgev41/MavenSplash)

I posted the isseu on [Stackoverflow ](https://stackoverflow.com/questions/48156911/java-maven-launch4j-no-splash-screen-same-jar-and-using-launch4j-gui-splash-scr) see , but no answers,

When build with Maven a JAR is generated.
- Run with Java -JAR: splash is OK.
- With the Lauch4J GUI application the EXE is build from the same JAR: splash is OK
- When build with the plug-in: splash NOT OK, not shown.

BTW for this example I used the code of [Github nicatronica](https://github.com/nicatronica/Java-Swing-Maven)

**Comment by lukaszlenart** [comment]
What system do you use the build the .exe? What system you run on?

**Comment by Forgev41** [comment]
I run on Windows 10 with Eclipse Oxygen. from December 2017. As far as I can see Maven 3.3.9 is installed

As I wrote, when testing with the standalone Launch4J, I used both 3.09 and 3.11

I tested on a different computer, a laptop and get different results.
On this computer the java - jar does also not work. Have to test further.
I get back to you.

**Comment by Forgev41** [comment]
As said I tested it on my Windows laptop with Java 9 and got no splash screen at all.
It appears that this was a bug in Java 9, see [JDK bug system](https://bugs.openjdk.java.net/browse/JDK-8190252).
Good news, it was repaired in the 9.0.4 version. Now on the command line the java -jar works again.

I tested the JAR build with Maven on these versions.
On all platforms the build JAR files shows the splash screen on start up when started with java -jar
So the JAR file build with maven is Ok.

**On the desktop I have:**
Windows 10, latest builds
Build with: 
- Eclipse Oxygen.2 Release (4.7.2)
- Compiled with: Java JDK: jdk1.8.0_91

Run on command line with: Java: JDK jdk1.8.0_91

**On the laptop**
Windows 10, latest builds
Build with: 
- Eclipse Oxygen.2 Release (4.7.2)
- Compiled with: Java JDK: jdk1.8.0_151

Run on command line with Java: 
1)	jre 9.0.4
2)	jre 1.8.0_151
3)	jre 1.7.0_79

**Apple MacBook Air with** 
Run jar with Java 8 update 101

On the Desktop: effective POM:
`<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.lvargas</groupId>
  <artifactId>Maven_Swing_HelloWorld</artifactId>
  <version>1.0-SNAPSHOT</version>
  <name>Splash</name>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <repositories>
    <repository>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>central</id>
      <name>Central Repository</name>
      <url>https://repo.maven.apache.org/maven2</url>
    </repository>
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <releases>
        <updatePolicy>never</updatePolicy>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>central</id>
      <name>Central Repository</name>
      <url>https://repo.maven.apache.org/maven2</url>
    </pluginRepository>
  </pluginRepositories>
  <build>
    <sourceDirectory>D:\Source\Java\ClientApplications\JavaTest\Maven_Swing_HelloWorld\src\main\java</sourceDirectory>
    <scriptSourceDirectory>D:\Source\Java\ClientApplications\JavaTest\Maven_Swing_HelloWorld\src\main\scripts</scriptSourceDirectory>
    <testSourceDirectory>D:\Source\Java\ClientApplications\JavaTest\Maven_Swing_HelloWorld\src\test\java</testSourceDirectory>
    <outputDirectory>D:\Source\Java\ClientApplications\JavaTest\Maven_Swing_HelloWorld\target\classes</outputDirectory>
    <testOutputDirectory>D:\Source\Java\ClientApplications\JavaTest\Maven_Swing_HelloWorld\target\test-classes</testOutputDirectory>
    <resources>
      <resource>
        <directory>D:\Source\Java\ClientApplications\JavaTest\Maven_Swing_HelloWorld\src\main\resources</directory>
      </resource>
    </resources>
    <testResources>
      <testResource>
        <directory>D:\Source\Java\ClientApplications\JavaTest\Maven_Swing_HelloWorld\src\test\resources</directory>
      </testResource>
    </testResources>
    <directory>D:\Source\Java\ClientApplications\JavaTest\Maven_Swing_HelloWorld\target</directory>
    <finalName>Maven_Swing_HelloWorld-1.0-SNAPSHOT</finalName>
    <pluginManagement>
      <plugins>
        <plugin>
          <artifactId>maven-antrun-plugin</artifactId>
          <version>1.3</version>
        </plugin>
        <plugin>
          <artifactId>maven-assembly-plugin</artifactId>
          <version>2.2-beta-5</version>
        </plugin>
        <plugin>
          <artifactId>maven-dependency-plugin</artifactId>
          <version>2.8</version>
        </plugin>
        <plugin>
          <artifactId>maven-release-plugin</artifactId>
          <version>2.3.2</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <artifactId>maven-jar-plugin</artifactId>
        <version>2.4</version>
        <executions>
          <execution>
            <id>default-jar</id>
            <phase>package</phase>
            <goals>
              <goal>jar</goal>
            </goals>
            <configuration>
              <archive>
                <manifest>
                  <addClasspath>true</addClasspath>
                  <classpathPrefix>lib/</classpathPrefix>
                  <mainClass>com.lvargas.helloworld_01.MainFrame</mainClass>
                </manifest>
                <manifestEntries>
                  <SplashScreen-Image>splash.png</SplashScreen-Image>
                </manifestEntries>
              </archive>
              <finalName>Splash</finalName>
            </configuration>
          </execution>
        </executions>
        <configuration>
          <archive>
            <manifest>
              <addClasspath>true</addClasspath>
              <classpathPrefix>lib/</classpathPrefix>
              <mainClass>com.lvargas.helloworld_01.MainFrame</mainClass>
            </manifest>
            <manifestEntries>
              <SplashScreen-Image>splash.png</SplashScreen-Image>
            </manifestEntries>
          </archive>
          <finalName>Splash</finalName>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>2.5.1</version>
        <executions>
          <execution>
            <id>copy-dependencies</id>
            <phase>package</phase>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <outputDirectory>D:\Source\Java\ClientApplications\JavaTest\Maven_Swing_HelloWorld\target/lib/</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>com.akathist.maven.plugins.launch4j</groupId>
        <artifactId>launch4j-maven-plugin</artifactId>
        <version>1.7.21</version>
        <executions>
          <execution>
            <id>Splash</id>
            <phase>package</phase>
            <goals>
              <goal>launch4j</goal>
            </goals>
            <configuration>
              <headerType>gui</headerType>
              <jar>D:\Source\Java\ClientApplications\JavaTest\Maven_Swing_HelloWorld\target/Splash.jar</jar>
              <outfile>D:\Source\Java\ClientApplications\JavaTest\Maven_Swing_HelloWorld\target/Splash_Maven.exe</outfile>
              <downloadUrl>http://java.com/download</downloadUrl>
              <classPath>
                <mainClass>com.lvargas.helloworld_01.MainFrame</mainClass>
              </classPath>
              <icon>D:\Source\Java\ClientApplications\JavaTest\Maven_Swing_HelloWorld\src\main\resources\logo alone.ico</icon>
              <jre>
                <minVersion>1.8.0</minVersion>
                <jdkPreference>preferJre</jdkPreference>
              </jre>
              <versionInfo>
                <fileVersion>1.0.0.0</fileVersion>
                <txtFileVersion>1.0-SNAPSHOT</txtFileVersion>
                <fileDescription>Splash</fileDescription>
                <copyright>2017 LightroomStatistics</copyright>
                <productVersion>1.0.0.0</productVersion>
                <txtProductVersion>1.0.0.0</txtProductVersion>
                <productName>Splash</productName>
                <companyName>LightroomStatistics.com</companyName>
                <internalName>LightroomStatistics</internalName>
                <originalFilename>LR-Analyzer.exe</originalFilename>
              </versionInfo>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-clean-plugin</artifactId>
        <version>2.5</version>
        <executions>
          <execution>
            <id>default-clean</id>
            <phase>clean</phase>
            <goals>
              <goal>clean</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-resources-plugin</artifactId>
        <version>2.6</version>
        <executions>
          <execution>
            <id>default-testResources</id>
            <phase>process-test-resources</phase>
            <goals>
              <goal>testResources</goal>
            </goals>
          </execution>
          <execution>
            <id>default-resources</id>
            <phase>process-resources</phase>
            <goals>
              <goal>resources</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.1</version>
        <executions>
          <execution>
            <id>default-compile</id>
            <phase>compile</phase>
            <goals>
              <goal>compile</goal>
            </goals>
          </execution>
          <execution>
            <id>default-testCompile</id>
            <phase>test-compile</phase>
            <goals>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.12.4</version>
        <executions>
          <execution>
            <id>default-test</id>
            <phase>test</phase>
            <goals>
              <goal>test</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-install-plugin</artifactId>
        <version>2.4</version>
        <executions>
          <execution>
            <id>default-install</id>
            <phase>install</phase>
            <goals>
              <goal>install</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-deploy-plugin</artifactId>
        <version>2.7</version>
        <executions>
          <execution>
            <id>default-deploy</id>
            <phase>deploy</phase>
            <goals>
              <goal>deploy</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-site-plugin</artifactId>
        <version>3.3</version>
        <executions>
          <execution>
            <id>default-site</id>
            <phase>site</phase>
            <goals>
              <goal>site</goal>
            </goals>
            <configuration>
              <outputDirectory>D:\Source\Java\ClientApplications\JavaTest\Maven_Swing_HelloWorld\target\site</outputDirectory>
              <reportPlugins>
                <reportPlugin>
                  <groupId>org.apache.maven.plugins</groupId>
                  <artifactId>maven-project-info-reports-plugin</artifactId>
                </reportPlugin>
              </reportPlugins>
            </configuration>
          </execution>
          <execution>
            <id>default-deploy</id>
            <phase>site-deploy</phase>
            <goals>
              <goal>deploy</goal>
            </goals>
            <configuration>
              <outputDirectory>D:\Source\Java\ClientApplications\JavaTest\Maven_Swing_HelloWorld\target\site</outputDirectory>
              <reportPlugins>
                <reportPlugin>
                  <groupId>org.apache.maven.plugins</groupId>
                  <artifactId>maven-project-info-reports-plugin</artifactId>
                </reportPlugin>
              </reportPlugins>
            </configuration>
          </execution>
        </executions>
        <configuration>
          <outputDirectory>D:\Source\Java\ClientApplications\JavaTest\Maven_Swing_HelloWorld\target\site</outputDirectory>
          <reportPlugins>
            <reportPlugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-project-info-reports-plugin</artifactId>
            </reportPlugin>
          </reportPlugins>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <reporting>
    <outputDirectory>D:\Source\Java\ClientApplications\JavaTest\Maven_Swing_HelloWorld\target\site</outputDirectory>
  </reporting>
</project>
`

**Comment by Forgev41** [comment]
Wrong click

**Comment by lukaszlenart** [comment]
Looks like this issue can be closed, right?

**Comment by Forgev41** [comment]
No, as far is I can see the launch4j-maven-plugin does not generate an EXE with a splash screen.
What I tried to prove was that generated JAR file does contain a splash screen which functions properly but the generated EXE does NOT show the splash screen. So the problem is still there.

Could you reproduce with the provided sample project / repository?

**Comment by lukaszlenart** [comment]
I do not see a `<splash/>` section in your pom:

```xml
<splash>
    <file>file</file>
    <waitForWindow>true|false</waitForWindow>
    <timeout>seconds [60]</timeout>
    <timeoutErr>true|false</timeoutErr>
  </splash>
```

**Comment by Forgev41** [comment]
Thanks, adding the splash section solved the problem **partly**. A splash screen is shown.
So for that the issue can be closed!

By partly I mean, that only a BMP file can be specified and it will show at startup. Fine.
However no splash screen with transparency can be displayed when using BMP.

In my setup I specify the splash in the manifest file and it is available when the final JAR is run with JAVA -JAR. Here I can use a PNG file, as in the supplied Github project.

When using the Launch4j GUI application, I do not specify any splash information and I also do not provide a BMP file. In the "Splash" tab I have the "Enable splash screen" unchecked.
Yet, we generating the EXE the PNG splash is used and shown. 
So in this setup I can use and PNG file with transparency.

Would be nice that the plugin would have the same behavior as the GUI version of Launch4J! That is what I was expecting and that's why I didn't use the splash section, because I didn't use it in the GUI version.

**Comment by lukaszlenart** [comment]
I'm not sure what's the difference, the plugin just generates an Ant config (it's the only way to configure Launch4j) and calls Launch4j. Maybe Launch4j works in different way when using Ant configuration.

**Comment by lukaszlenart** [comment]
I found the problem, it is in your configuration. The splash screen works because it is defined in a `MANIFEST.MF` file inside the jar. So launching the jar with `java -jar your.jar` tells Java to use jar's MANIFEST file to search for a main class and other options. In your configuration you have defined the main class directly which means when launching the app a different method will be used which omits the `MANIFEST.MF` file, i.e.: `java com.app.YourMainClass -cp your.jar`. To resolve that problem you cannot specify the `mainClass` option in the config, see below:
```xml
<configuration>
  <headerType>gui</headerType>
  <jar>${project.basedir}/target/${project.name}.jar</jar>
  <downloadUrl>http://java.com/download</downloadUrl>
  <!-- Update to the local resource path -->
  <icon>${project.basedir}/src/main/resources/logo_alone.ico</icon>
  <jre>
    <minVersion>1.8.0</minVersion>
    <jdkPreference>preferJre</jdkPreference>
  </jre>
  <versionInfo>
    <fileVersion>1.0.0.0</fileVersion>
    <txtFileVersion>${project.version}</txtFileVersion>
    <fileDescription>${project.name}</fileDescription>
    <copyright>2017 LightroomStatistics</copyright>
    <productVersion>1.0.0.0</productVersion>
    <txtProductVersion>1.0.0.0</txtProductVersion>
    <productName>${project.name}</productName>
    <companyName>LightroomStatistics.com</companyName>
    <internalName>LightroomStatistics</internalName>
    <originalFilename>LR-Analyzer.exe</originalFilename>
  </versionInfo>
</configuration>
```

**Comment by Forgev41** [comment]
Awesome! Thanks very much for solving this issue!

I updated the Stackoverflow question with your answer!

**Comment by pupeno** [comment]
Does specifying the mainClass make Java ignore the splash screen defined in the manifest?

**Comment by lukaszlenart** [comment]
Yes, because then the jar is placed on a classpath and not used directly. So Java does not scan for `MANIFEST` files inside jars on the classpath.
