### ISSUE TITLE
Program Compatibility Assistant

### ISSUE THREAD

**Issue by rwapshott** [lukaszlenart/launch4j-maven-plugin#70]
Hello,

Testing a GUI on Windows 7, it looks like the generated executable triggers the Windows Program Compatibility Assistant.

Related Launch4J bug: https://sourceforge.net/p/launch4j/bugs/87/
Related Stackoverflow: https://stackoverflow.com/questions/806017/why-i-receive-a-message-from-the-program-compatibility-assistant#3329886

It appears we need to include a manifest file in the compiled executable. How do we configure the Maven plugin to do this?

If I use the <manifest> tag with a file named as per the Javadoc, I get this error:

> The application has failed to start because its side-by-side configuration is in correct. Please see the application event log or use the command-line sxstrace.exe

Any suggestions would be appreciated!

Thanks!

**Comment by lukaszlenart** [comment]
I think the problem is that Launch4j itself doesn't support embedding manifest into a generated exe, so plugin won't help here.

**Comment by rwapshott** [comment]
Ok, thanks that is helpful.
