### ISSUE TITLE
Using -T NNN with maven build can cause launch4j plugin to fail

### ISSUE THREAD

**Issue by kwesterfeld2** [lukaszlenart/launch4j-maven-plugin#72]
Using parallel execution for a multi-module project that generates multiple .exe using launch4j fails randomly.  This is because the launch4j plugin is not thread-safe.  It would be great if there was some synchronization put in place to prevent clobbering the execution of multiple simultaneous modules generating .exe.

**Comment by lukaszlenart** [comment]
I am not sure if this is possible, I meant the only option I see is a lock file that will allow one execution of the plugin in given time.

**Comment by lukaszlenart** [comment]
Could you test 1.7.22-SNAPSHOT? I have added a `parallelExecution` flag that will allow to run only one instance of the plugin in the given time. This should resolve the issue with blocking on resources.

**Comment by lukaszlenart** [comment]
See https://github.com/lukaszlenart/launch4j-maven-plugin/pull/73

**Comment by lukaszlenart** [comment]
PR got merged, I will prepare a new release soon

**Comment by kwesterfeld2** [comment]
Sorry, just now getting back to this.  I am using the latest launch4j version (1.7.23) and added the parallelExecution flag, but Maven still gripes:

```
[INFO] ------------------------------------------------------------------------
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in Yellowbrick - Tools:
[WARNING] com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:1.7.23
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
[WARNING] *****************************************************************
```

**Comment by lukaszlenart** [comment]
1.7.24 is under way to the Central, please check and report back, thanks :)

**Comment by kwesterfeld2** [comment]
Thanks !

On Oct 26, 2018, at 12:02 PM, Lukasz Lenart <notifications@github.com<mailto:notifications@github.com>> wrote:


1.7.24 is under way to the Central, please check and report back, thanks :)
