### ISSUE TITLE
Update to launch4j 3.12

### ISSUE THREAD

**Issue by tofi86** [lukaszlenart/launch4j-maven-plugin#75]
Launch4j 3.12 was released with support for Java 9 and 10:
http://launch4j.sourceforge.net/changelog.html

Any chance to release a new version of the plugin anytime soon?

Thanks!

**Comment by lukaszlenart** [comment]
I've been waiting when it will be available in the Maven Central - it is now so I can start a new release ;-)
https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22net.sf.launch4j%22%20AND%20a%3A%22launch4j%22

**Comment by lukaszlenart** [comment]
Launch4j Maven plugin version 1.7.22 is under way to the Central :) Enjoy!

**Comment by tofi86** [comment]
Awesome, thanks! 🎉
