### ISSUE TITLE
versionInfo mandates version as x.x.x.x

### ISSUE THREAD

**Issue by MkJha** [lukaszlenart/launch4j-maven-plugin#77]
a. versionInfo is optional as per http://launch4j.sourceforge.net/docs.html, but why does the plugin mandates it ?

b. Typically an project/module version is used for version info, but is module maintains version in x.x.x, then user has to use a different version x.x.x.x for exe version info, leading to discrepancy in readability. 

c. what is fileVersion and product version ?

**Comment by lukaszlenart** [comment]
a) can be easily resolved

b) do not understand

c) https://docs.microsoft.com/en-us/windows/desktop/menurc/versioninfo-resource

**Comment by MkJha** [comment]
After reading document, i got clarity. thanks!!
