### ISSUE TITLE
Error while starting window service for exe(generated) by Luanch4j ?

### ISSUE THREAD

**Issue by MkJha** [lukaszlenart/launch4j-maven-plugin#78]
I have generated exe(xyz.exe) using launch4j and create window service using window command "sc create xyzSrv binPath= c:/users/.../xyz.exe". service gets created successfully.  but while starting service i get the below error:

[SC] StartService FAILED 1053:

The service did not respond to the start or control request in a timely fashion.

I read at https://sourceforge.net/p/launch4j/feature-requests/56/ .(is this related to this use case)

Could you please conclude on this ?

**Comment by lukaszlenart** [comment]
If the original Launch4j doesn't support this, I mean creating a service wrapper, the plugin won't help as well. The plugin is just a Maven wrapper around Launch4j.
