### ISSUE TITLE
customProcName support required

### ISSUE THREAD

**Issue by piyengar** [lukaszlenart/launch4j-maven-plugin#79]
The plugin does not support the property `customProcName`.
Would it be possible to support it?

**Comment by lukaszlenart** [comment]
PRs are welcome :)

**Comment by lukaszlenart** [comment]
As far I see, launch4j doesn't support such option, what did you mean by `customProcName`?
http://launch4j.sourceforge.net/docs.html

**Comment by piyengar** [comment]
I think you are right, and it's been such a long time since I even worked on the project where I needed this. I am closing this.
