### ISSUE TITLE
App doesnt launch on MacOS with JDK11

### ISSUE THREAD

**Issue by eitzenbe** [lukaszlenart/launch4j-maven-plugin#83]
As of recently Oracle has forced MacOS users to download JDK11 and not anymore 10.0.2, which is troublesome as the app created by launch4j (exactly the JavaAppLauncher) fails with JDK11 installed

Any update on whetehr JDK11 is on the roadmap to be supported?

**Comment by lukaszlenart** [comment]
But this is rather Launch4j issue than the plugin.

**Comment by eitzenbe** [comment]
1:0 you got a point there, will report it on the project there ;)

**Comment by lukaszlenart** [comment]
2.0.1 is out, you can try to use it.
