### ISSUE TITLE
Window title

### ISSUE THREAD

**Issue by aunkrig** [lukaszlenart/launch4j-maven-plugin#97]
Thank you for this wonderful tool! I'm using it successfully for [autoauth](https://github.com/aunkrig/autoauth) and the [zz tools](https://zz.unkrig.de).

When I configure an icon, then it appears very nicely in the window title bar and in the task switcher. But how can I set the *window title*? I'd expect a "<title>" element in the mvn configuration!?

**Comment by lukaszlenart** [comment]
You must define a `<singleInstance>` section and then define `<windowTitle>` property inside it.
That's how it was defined in Launch4j
http://launch4j.sourceforge.net/docs.html

**Comment by aunkrig** [comment]
Hey Lukasz,

The documentation says something different:

<singleInstance>
Optional, allow to run only a single instance of the application.
[...]
<windowTitle>
Optional, recognized by GUI header only. Title or title part of a window to bring up instead of running a new instance.

**Comment by lukaszlenart** [comment]
This plugin is just a wrapper around Launch4j, if that project doesn't provide such functionality it won't be available auto-magically here.

**Comment by aunkrig** [comment]
Thank you. I'll turn to the l4j people.
